kind: Service
apiVersion: v1
metadata:
  name: ngservice-c-public
  namespace: polyglot
  labels:
    app: ngservice-c
spec:
  type: LoadBalancer
  selector:
    app: ngservice-c
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ngservice-c
  namespace: polyglot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngservice-c
  template:
    metadata:
      labels:
        app: ngservice-c
        version: v1
    spec:
      containers:
        - name: ngservice-c
          image: tuxtor/ngservice-c:oci-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
