kind: Service
apiVersion: v1
metadata:
  name: kservice-a
  namespace: polyglot
  labels:
    app: kservice-a
spec:
  type: ClusterIP
  selector:
    app: kservice-a
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kservice-a
  namespace: polyglot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kservice-a
  template:
    metadata:
      labels:
        app: kservice-a
        version: v1
    spec:
      containers:
      - name: kservice-a
        image: tuxtor/kservice-a:oci-1.0.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
