kind: Service
apiVersion: v1
metadata:
  name: jservice-b
  namespace: polyglot
  labels:
    app: jservice-b
spec:
  type: ClusterIP
  selector:
    app: jservice-b
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Service
apiVersion: v1
metadata:
  name: jservice-b-public
  namespace: polyglot
  labels:
    app: jservice-b-public
spec:
  type: LoadBalancer
  selector:
    app: jservice-b
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jservice-b
  namespace: polyglot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jservice-b
  template:
    metadata:
      labels:
        app: jservice-b
        version: v1
    spec:
      containers:
      - name: jservice-b
        image: tuxtor/jservice-b:laouc-1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
